/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import javax.swing.JOptionPane;

/**
 *
 * @author junio
 */
public class Login extends javax.swing.JFrame {
    
    HomePage home = new HomePage();
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonEsquecer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        buttonEntrar = new javax.swing.JToggleButton();
        textLogin = new javax.swing.JTextField();
        textSenha = new javax.swing.JTextField();
        labelLogin = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        buttonCadastro = new javax.swing.JButton();
        fundotransparente = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonEsquecer.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        buttonEsquecer.setForeground(new java.awt.Color(255, 255, 255));
        buttonEsquecer.setText("Esqueceu sua senha?");
        buttonEsquecer.setContentAreaFilled(false);
        buttonEsquecer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEsquecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEsquecerActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEsquecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 120, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Não tem cadastro?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        buttonEntrar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        buttonEntrar.setText("Entrar");
        buttonEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 110, 30));

        textLogin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(textLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 150, 20));

        textSenha.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        textSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(textSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 150, 20));

        labelLogin.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        labelLogin.setText("Login");
        jPanel1.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));
        labelLogin.getAccessibleContext().setAccessibleName("Senha");

        labelSenha.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        labelSenha.setText("Senha");
        jPanel1.add(labelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        logo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logo.setText("LOGO AQUI");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 140, 50));

        buttonCadastro.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        buttonCadastro.setForeground(new java.awt.Color(255, 255, 255));
        buttonCadastro.setText("Crie sua conta");
        buttonCadastro.setContentAreaFilled(false);
        buttonCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 120, 60));

        fundotransparente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Imagem/Design sem nome (7).png"))); // NOI18N
        fundotransparente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fundotransparente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(fundotransparente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 200, 300));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Imagem/Fundo800X600.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1915, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(816, 606));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSenhaActionPerformed

    private void buttonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastroActionPerformed
        // TODO add your handling code here:
        Cadastro cadastro = new Cadastro();
        cadastro.setVisible(true);
    }//GEN-LAST:event_buttonCadastroActionPerformed

    private void buttonEsquecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEsquecerActionPerformed
        // TODO add your handling code here:
        Redefinir redefinir = new Redefinir();
        redefinir.setVisible(true);
    }//GEN-LAST:event_buttonEsquecerActionPerformed

    private void buttonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEntrarActionPerformed
        // TODO add your handling code here:
        String login = textLogin.getText();
        String senha = textSenha.getText();
        //HomePage home = new HomePage();
        
        if (("usuario".equals(login)) && ("123".equals(senha))){
            home.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuário não encontrado. Verifique suas credenciais ou cadastre-se.", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton buttonCadastro;
    private javax.swing.JToggleButton buttonEntrar;
    private javax.swing.JButton buttonEsquecer;
    private javax.swing.JLabel fundotransparente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField textLogin;
    private javax.swing.JTextField textSenha;
    // End of variables declaration//GEN-END:variables
}
