/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

/**
 *
 * @author junio
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonEsquecer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        buttonEntrar = new javax.swing.JToggleButton();
        textLogin = new javax.swing.JTextField();
        textSenha = new javax.swing.JTextField();
        labelLogin = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        buttonCadastro = new javax.swing.JButton();
        fundotransparente = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonEsquecer.setForeground(new java.awt.Color(255, 255, 255));
        buttonEsquecer.setText("Esqueceu sua senha?");
        buttonEsquecer.setContentAreaFilled(false);
        buttonEsquecer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEsquecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEsquecerActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEsquecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Não tem cadastro?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 610, -1, -1));

        buttonEntrar.setText("Entrar");
        buttonEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(buttonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 130, 40));
        jPanel1.add(textLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 400, 210, 30));

        textSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(textSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 210, 30));

        labelLogin.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        labelLogin.setText("Login");
        jPanel1.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, -1, -1));
        labelLogin.getAccessibleContext().setAccessibleName("Senha");

        labelSenha.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        labelSenha.setText("Senha");
        jPanel1.add(labelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, -1, -1));

        logo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        logo.setText("LOGO AQUI");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, -1, -1));

        buttonCadastro.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        buttonCadastro.setForeground(new java.awt.Color(255, 255, 255));
        buttonCadastro.setText("Crie sua conta");
        buttonCadastro.setContentAreaFilled(false);
        buttonCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(buttonCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 590, 120, 60));

        fundotransparente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Imagem/Site para Link na Bio Tecnologia e Jogos Escuro Simples Azul-escuro (5).png"))); // NOI18N
        fundotransparente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fundotransparente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(fundotransparente, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 400, 600));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/Imagem/835be700-18e5-4884-b06a-dd5394305b2d.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1960, 1200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1915, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1931, 1091));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSenhaActionPerformed

    private void buttonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastroActionPerformed
        // TODO add your handling code here:
        Cadastro cadastro = new Cadastro();
        cadastro.setVisible(true);
    }//GEN-LAST:event_buttonCadastroActionPerformed

    private void buttonEsquecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEsquecerActionPerformed
        // TODO add your handling code here:
        Redefinir redefinir = new Redefinir();
        redefinir.setVisible(true);
    }//GEN-LAST:event_buttonEsquecerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton buttonCadastro;
    private javax.swing.JToggleButton buttonEntrar;
    private javax.swing.JButton buttonEsquecer;
    private javax.swing.JLabel fundotransparente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField textLogin;
    private javax.swing.JTextField textSenha;
    // End of variables declaration//GEN-END:variables
}
